#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#此配置优高于@RibbonClient，低于@RibbonClients配置
news:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule